### ISSUE TITLE
[hoodie-account-server] replace "pouchdb" with "pouchdb-core", "pouchdb-mapreduce" and "pouchdb-adapter-memory" 

### ISSUE THREAD

**Issue by LowProfileDog** [hoodiehq/camp#59] opened 2016-10-15 20:28 UTC
### 🎃💻👕 Hacktoberfest: Trick or Treat!

If you haven’t yet, sign up for [Hacktoberfest](https://hacktoberfest.digitalocean.com/) to earn an exclusive T-Shirt. Plus I’m sure we can teach you a cool trick or two in the process
### 🤔 What you will need to know

You should have worked with JavaScript, Node.js and Testing. If you haven’t yet, we recommend the [JavaScript Track on exercism.io](http://exercism.io/languages/javascript)

[hoodie-account-server](https://github.com/hoodiehq/hoodie-account-server) currently has [PouchDB in its devDependencies](https://github.com/hoodiehq/hoodie-account-server/blob/69fbe3437b7a06725919f8e356f9833806249fec/package.json#L50). We need PouchDB for testing.

But [pouchdb](https://www.npmjs.com/package/pouchdb) comes with all sorts of features that we don’t need, but they slow down the installation time and also install native dependencies that are sometimes hard to setup, especially on older windows machines. 

Luckily, our friends at PouchDB created [custom builds](https://pouchdb.com/custom.html). That allows us to only pick exactly the features that we need, which are 
- [pouchdb-core](https://www.npmjs.com/package/pouchdb-core)
- [pouchdb-mapreduce](https://www.npmjs.com/package/pouchdb-mapreduce)
- [pouchdb-adapter-memory](https://www.npmjs.com/package/pouchdb-adapter-memory)
### 🎯  The Goal

Minimise the installation time and requirements by replacing the `pouchdb` package with the packages listed above.
### :clipboard: Step by Step

If this is your first, welcome :tada: :smile: [Here is a great tutorial](https://egghead.io/series/how-to-contribute-to-an-open-source-project-on-github) on how to send a pull request using the terminal.
- [x] 🙋 **Claim this issue**: Comment below (or assign yourself and continue at step 4 :)  
  Please 🙏 only claim if you want to start working on it during the event.  
  Once claimed we add you as contributor to this repository.
- [x] 👌 **Accept our invitation** to this repository. Once accepted, assign yourself to this repository
- [x] 👓 **Please review** our [Code of Conduct](http://hood.ie/code-of-conduct/)  
  In a nutshell: be patient and actively kind with us 😊
- [x] 🔄 **replace** the `up for grabs` label with `in progress`.
- [x] 🗜 [**Setup the repository locally**](https://github.com/hoodiehq/hoodie-account-server/tree/master/tests#testing) make sure that all tests pass
- [x] replace `pouchdb` with the other packages in [package.json](https://github.com/hoodiehq/hoodie-account-server/blob/a282f40122dd29df25cf699071bbd979b3ff25af/package.json#L50) and [tests/integration/utils/get-server.js#L6](https://github.com/hoodiehq/hoodie-account-server/blob/a282f40122dd29df25cf699071bbd979b3ff25af/tests/integration/utils/get-server.js#L6)
- [x] **Commit the change** with `test: replace pouchdb with custom build for testing` and push it either to your fork or push your new branch.
- [x] 🔀 **Start a Pull Request**. Mention `closes hoodiehq/camp#59` in the description.  
- [x] 🏁 **Done** :+1: Replace the `in progress` label with `ready`. Ask in comments for a review :)
### 🤔❓ Questions

Ping us in the [Hoodie Chat](http://hood.ie/chat/) or on [Twitter](https://twitter.com/hoodiehq/)

**Comment by nistath** [comment] 2016-10-20 15:08
I can work on this!

**Comment by nistath** [comment] 2016-10-20 15:47
I wrote the code required a while ago, but the testing process is kind of confusing, as it gets stuck at the `Reading TAP data from stdin (use "-" argument to suppress)` part, where all it does is mirror what I write in stdin.

**Comment by LowProfileDog** [comment] 2016-10-21 04:01
Thanks for looking into it @nistath The issue is all yours :) I’ve invited you to our Camp repository, you can accept my invitation at https://github.com/hoodiehq/camp/invitations

Once accepted, you can assign yourself to this issue and check off the checkboxes above. Enjoy 🐕

Can you tell us your node & npm version? Run `npm -v` and `node -v`

**Comment by nistath** [comment] 2016-10-22 10:49
@LowProfileDog Here's what happens when I run the test.

$ npm test

> @hoodie/account-server@0.0.0-semantically-released pretest C:\Users\Nick\Deskt                 op\hoodie\hoodie-account-server
> standard

> @hoodie/account-server@0.0.0-semantically-released test C:\Users\Nick\Desktop\                 hoodie\hoodie-account-server
> nyc tap 'tests/{unit,integration}/*_/_-test.js'

Reading TAP data from stdin (use "-" argument to suppress)
asdasdasdas
asdasdasdas

and it keeps mirroring my input forever.

**Comment by nistath** [comment] 2016-10-22 11:01
The problem is that this works even if pouchdb is not installed. I have no idea if my new code works or not, although it is written according to the pouchdb documentation.

**Comment by nistath** [comment] 2016-10-22 11:05
I'm on node 6.5.0 and npm 3.10.3 on Windows 8.

**Comment by gr2m** [comment] 2016-10-22 18:04
@nistath I don’t know why the test is behaving that way for you yet, I’ve never seen that behavior before. 

One thinking mistake I found is that we don’t want the memory adapter, instead we want the [http adapter](https://www.npmjs.com/package/pouchdb-adapter-http), otherwise PouchDB won’t send requests and our CouchDB mocks will stop working

You can also try to run a single test. I’m not sure if it’s the same on Windows, but on mac you can execute the binary from the node_modules folder directly, for example

``` bash
./node_modules/.bin/tap tests/integration/routes/no-cookie-header-test.js
```

Will only run the tests defined in `tests/integration/routes/no-cookie-header-test.js`

Can you check if that helps in any way?

**Comment by gr2m** [comment] 2016-10-22 22:51
yeah fix was simple, I updated your PR: https://github.com/hoodiehq/hoodie-account-server/pull/213 and will merge it once CI passes, thanks :)

**Comment by nistath** [comment] 2016-10-23 06:52
That specific test ran successfully. I think there's one test that does that, and goes in an infinite loop not letting the other tests run. Either that, or TAP has some issues.

**Comment by gr2m** [comment] 2016-10-23 22:21
all good, fixed via https://github.com/hoodiehq/hoodie-account-server/pull/213

**Closed as completed by gr2m** 2016-10-23 22:21 UTC
Labels: Code
